#./configure \
#--with-config-file-path=/etc \
#--with-config-file-scan-dir=/etc/php.d \
#--with-pear \
#--with-curl \
#--with-gd \
#--with-jpeg-dir \
#--with-png-dir \
#--with-freetype-dir \
#--with-zlib-dir \
#--with-iconv \
#--with-mcrypt \
#--with-mhash \
#--with-pdo-mysql \
#--with-mysql-sock=/var/lib/mysql/mysql.sock \
#--with-openssl \
#--with-xsl \
#--with-recode \
#--enable-sockets \
#--enable-soap \
#--enable-mbstring \
#--enable-gd-native-ttf \
#--enable-zip \
#--enable-xml \
#--enable-bcmath \
#--enable-calendar \
#--enable-shmop \
#--enable-dba \
#--enable-wddx \
#--enable-sysvsem \
#--enable-sysvshm \
#--enable-sysvmsg \
#--enable-opcache \
#--enable-pcntl \
#--enable-maintainer-zts \

./configure \
--with-config-file-path=/tmp/php/etc \
--with-config-file-scan-dir=/tmp/php/etc/php.d \
--prefix=/tmp/php \
--enable-maintainer-zts \
--with-openssl \
--with-zlib \
--with-bz2 \
--enable-zip \
--with-pdo-mysql \
--with-gd \
--enable-mbstring \
--with-freetype-dir \
--enable-gd-native-ttf \
--with-jpeg-dir \
--with-png-dir \
